version: "3"
# The parser will ignore extension fields prefixed with x-
x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopped 

services:
  mysql:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    networks: ["wordpress"]
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"

  wordpress:
    depends_on: ["mysql"]
    image: wordpress:php8.2-apache
    volumes:
      - wp_data:/var/www/html
    networks: ["wordpress"]
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://127.0.0.1/wp-admin/install.php/ | grep 'Продолжить' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 2

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on: ["mysql"]
    ports: ["80:80"]
    networks: ["wordpress"]



volumes:
  db_data: {}
  wp_data: {}
networks:
  wordpress:
    name: wordpress

